name = "hustlesynth-main"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[[redirects]]
from = "/api/*"
to = "https://api.hustlesynth.space/:splat"
status = 200

[env.production]
vars = { ENVIRONMENT = "production" }